import timer from "./modules/timer";
import menu from "./modules/menu";
import modal from "./modules/modal";
import anchorsAnimate from "./modules/anchors";
import validation from "./modules/validation";
timer("28 february 2023");
menu();
modal();
anchorsAnimate();
validation();
